server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/test/**

        - id: products-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**